//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ficha20.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Operacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float Num1Field;
        
        private float Num2Field;
        
        private float ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Num1 {
            get {
                return this.Num1Field;
            }
            set {
                if ((this.Num1Field.Equals(value) != true)) {
                    this.Num1Field = value;
                    this.RaisePropertyChanged("Num1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Num2 {
            get {
                return this.Num2Field;
            }
            set {
                if ((this.Num2Field.Equals(value) != true)) {
                    this.Num2Field = value;
                    this.RaisePropertyChanged("Num2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceCalculadoraSoap")]
    public interface WebServiceCalculadoraSoap {
        
        // CODEGEN: Generating message contract since element name SomaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soma", ReplyAction="*")]
        Ficha20.ServiceReference1.SomaResponse Soma(Ficha20.ServiceReference1.SomaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soma", ReplyAction="*")]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.SomaResponse> SomaAsync(Ficha20.ServiceReference1.SomaRequest request);
        
        // CODEGEN: Generating message contract since element name SubtracaoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtracao", ReplyAction="*")]
        Ficha20.ServiceReference1.SubtracaoResponse Subtracao(Ficha20.ServiceReference1.SubtracaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtracao", ReplyAction="*")]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.SubtracaoResponse> SubtracaoAsync(Ficha20.ServiceReference1.SubtracaoRequest request);
        
        // CODEGEN: Generating message contract since element name MultiplicacaoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacao", ReplyAction="*")]
        Ficha20.ServiceReference1.MultiplicacaoResponse Multiplicacao(Ficha20.ServiceReference1.MultiplicacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.MultiplicacaoResponse> MultiplicacaoAsync(Ficha20.ServiceReference1.MultiplicacaoRequest request);
        
        // CODEGEN: Generating message contract since element name DivisaoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divisao", ReplyAction="*")]
        Ficha20.ServiceReference1.DivisaoResponse Divisao(Ficha20.ServiceReference1.DivisaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divisao", ReplyAction="*")]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.DivisaoResponse> DivisaoAsync(Ficha20.ServiceReference1.DivisaoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Soma", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.SomaRequestBody Body;
        
        public SomaRequest() {
        }
        
        public SomaRequest(Ficha20.ServiceReference1.SomaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float num2;
        
        public SomaRequestBody() {
        }
        
        public SomaRequestBody(float num1, float num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.SomaResponseBody Body;
        
        public SomaResponse() {
        }
        
        public SomaResponse(Ficha20.ServiceReference1.SomaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SomaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ficha20.ServiceReference1.Operacao SomaResult;
        
        public SomaResponseBody() {
        }
        
        public SomaResponseBody(Ficha20.ServiceReference1.Operacao SomaResult) {
            this.SomaResult = SomaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtracaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Subtracao", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.SubtracaoRequestBody Body;
        
        public SubtracaoRequest() {
        }
        
        public SubtracaoRequest(Ficha20.ServiceReference1.SubtracaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtracaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float num2;
        
        public SubtracaoRequestBody() {
        }
        
        public SubtracaoRequestBody(float num1, float num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtracaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtracaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.SubtracaoResponseBody Body;
        
        public SubtracaoResponse() {
        }
        
        public SubtracaoResponse(Ficha20.ServiceReference1.SubtracaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtracaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ficha20.ServiceReference1.Operacao SubtracaoResult;
        
        public SubtracaoResponseBody() {
        }
        
        public SubtracaoResponseBody(Ficha20.ServiceReference1.Operacao SubtracaoResult) {
            this.SubtracaoResult = SubtracaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Multiplicacao", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.MultiplicacaoRequestBody Body;
        
        public MultiplicacaoRequest() {
        }
        
        public MultiplicacaoRequest(Ficha20.ServiceReference1.MultiplicacaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicacaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float num2;
        
        public MultiplicacaoRequestBody() {
        }
        
        public MultiplicacaoRequestBody(float num1, float num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplicacaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.MultiplicacaoResponseBody Body;
        
        public MultiplicacaoResponse() {
        }
        
        public MultiplicacaoResponse(Ficha20.ServiceReference1.MultiplicacaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicacaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ficha20.ServiceReference1.Operacao MultiplicacaoResult;
        
        public MultiplicacaoResponseBody() {
        }
        
        public MultiplicacaoResponseBody(Ficha20.ServiceReference1.Operacao MultiplicacaoResult) {
            this.MultiplicacaoResult = MultiplicacaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Divisao", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.DivisaoRequestBody Body;
        
        public DivisaoRequest() {
        }
        
        public DivisaoRequest(Ficha20.ServiceReference1.DivisaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float num2;
        
        public DivisaoRequestBody() {
        }
        
        public DivisaoRequestBody(float num1, float num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ficha20.ServiceReference1.DivisaoResponseBody Body;
        
        public DivisaoResponse() {
        }
        
        public DivisaoResponse(Ficha20.ServiceReference1.DivisaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ficha20.ServiceReference1.Operacao DivisaoResult;
        
        public DivisaoResponseBody() {
        }
        
        public DivisaoResponseBody(Ficha20.ServiceReference1.Operacao DivisaoResult) {
            this.DivisaoResult = DivisaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculadoraSoapChannel : Ficha20.ServiceReference1.WebServiceCalculadoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculadoraSoapClient : System.ServiceModel.ClientBase<Ficha20.ServiceReference1.WebServiceCalculadoraSoap>, Ficha20.ServiceReference1.WebServiceCalculadoraSoap {
        
        public WebServiceCalculadoraSoapClient() {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculadoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ficha20.ServiceReference1.SomaResponse Ficha20.ServiceReference1.WebServiceCalculadoraSoap.Soma(Ficha20.ServiceReference1.SomaRequest request) {
            return base.Channel.Soma(request);
        }
        
        public Ficha20.ServiceReference1.Operacao Soma(float num1, float num2) {
            Ficha20.ServiceReference1.SomaRequest inValue = new Ficha20.ServiceReference1.SomaRequest();
            inValue.Body = new Ficha20.ServiceReference1.SomaRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Ficha20.ServiceReference1.SomaResponse retVal = ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).Soma(inValue);
            return retVal.Body.SomaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.SomaResponse> Ficha20.ServiceReference1.WebServiceCalculadoraSoap.SomaAsync(Ficha20.ServiceReference1.SomaRequest request) {
            return base.Channel.SomaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ficha20.ServiceReference1.SomaResponse> SomaAsync(float num1, float num2) {
            Ficha20.ServiceReference1.SomaRequest inValue = new Ficha20.ServiceReference1.SomaRequest();
            inValue.Body = new Ficha20.ServiceReference1.SomaRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).SomaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ficha20.ServiceReference1.SubtracaoResponse Ficha20.ServiceReference1.WebServiceCalculadoraSoap.Subtracao(Ficha20.ServiceReference1.SubtracaoRequest request) {
            return base.Channel.Subtracao(request);
        }
        
        public Ficha20.ServiceReference1.Operacao Subtracao(float num1, float num2) {
            Ficha20.ServiceReference1.SubtracaoRequest inValue = new Ficha20.ServiceReference1.SubtracaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.SubtracaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Ficha20.ServiceReference1.SubtracaoResponse retVal = ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).Subtracao(inValue);
            return retVal.Body.SubtracaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.SubtracaoResponse> Ficha20.ServiceReference1.WebServiceCalculadoraSoap.SubtracaoAsync(Ficha20.ServiceReference1.SubtracaoRequest request) {
            return base.Channel.SubtracaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ficha20.ServiceReference1.SubtracaoResponse> SubtracaoAsync(float num1, float num2) {
            Ficha20.ServiceReference1.SubtracaoRequest inValue = new Ficha20.ServiceReference1.SubtracaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.SubtracaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).SubtracaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ficha20.ServiceReference1.MultiplicacaoResponse Ficha20.ServiceReference1.WebServiceCalculadoraSoap.Multiplicacao(Ficha20.ServiceReference1.MultiplicacaoRequest request) {
            return base.Channel.Multiplicacao(request);
        }
        
        public Ficha20.ServiceReference1.Operacao Multiplicacao(float num1, float num2) {
            Ficha20.ServiceReference1.MultiplicacaoRequest inValue = new Ficha20.ServiceReference1.MultiplicacaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.MultiplicacaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Ficha20.ServiceReference1.MultiplicacaoResponse retVal = ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).Multiplicacao(inValue);
            return retVal.Body.MultiplicacaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.MultiplicacaoResponse> Ficha20.ServiceReference1.WebServiceCalculadoraSoap.MultiplicacaoAsync(Ficha20.ServiceReference1.MultiplicacaoRequest request) {
            return base.Channel.MultiplicacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ficha20.ServiceReference1.MultiplicacaoResponse> MultiplicacaoAsync(float num1, float num2) {
            Ficha20.ServiceReference1.MultiplicacaoRequest inValue = new Ficha20.ServiceReference1.MultiplicacaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.MultiplicacaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).MultiplicacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ficha20.ServiceReference1.DivisaoResponse Ficha20.ServiceReference1.WebServiceCalculadoraSoap.Divisao(Ficha20.ServiceReference1.DivisaoRequest request) {
            return base.Channel.Divisao(request);
        }
        
        public Ficha20.ServiceReference1.Operacao Divisao(float num1, float num2) {
            Ficha20.ServiceReference1.DivisaoRequest inValue = new Ficha20.ServiceReference1.DivisaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.DivisaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Ficha20.ServiceReference1.DivisaoResponse retVal = ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).Divisao(inValue);
            return retVal.Body.DivisaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ficha20.ServiceReference1.DivisaoResponse> Ficha20.ServiceReference1.WebServiceCalculadoraSoap.DivisaoAsync(Ficha20.ServiceReference1.DivisaoRequest request) {
            return base.Channel.DivisaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ficha20.ServiceReference1.DivisaoResponse> DivisaoAsync(float num1, float num2) {
            Ficha20.ServiceReference1.DivisaoRequest inValue = new Ficha20.ServiceReference1.DivisaoRequest();
            inValue.Body = new Ficha20.ServiceReference1.DivisaoRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Ficha20.ServiceReference1.WebServiceCalculadoraSoap)(this)).DivisaoAsync(inValue);
        }
    }
}
